server:
  port: 8080

spring:
  datasource:
    username: root
    password: your_password
    url: jdbc:mysql://localhost:3306/task_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true